services:
  postgres:
    image: postgres:17
    container_name: odcs-odps-workshop-postgres
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop
      POSTGRES_DB: workshop
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./data:/data:ro
